import type { Client, DocumentRec, GlAccount } from "./types";

export const firm = { name: "易账", en: "Easetax", product: "AP 工作台" };

export const glAccounts: GlAccount[] = [
  { id: "6000", code: "6000", name: "办公用品 Office Supplies" },
  { id: "6010", code: "6010", name: "电话及网络 Telephone & Internet" },
  { id: "6020", code: "6020", name: "餐饮招待 Meals & Entertainment" },
  { id: "6030", code: "6030", name: "租金 Rent Expense" },
  { id: "6040", code: "6040", name: "软件订阅 Software & Subscriptions" },
  { id: "6050", code: "6050", name: "广告推广 Advertising & Promotion" },
  { id: "6060", code: "6060", name: "水电杂费 Utilities" },
  { id: "6070", code: "6070", name: "差旅 Travel" },
  { id: "6080", code: "6080", name: "专业服务费 Professional Fees" },
  { id: "6090", code: "6090", name: "银行手续费 Bank Charges" },
  { id: "6100", code: "6100", name: "保险 Insurance" },
  { id: "6110", code: "6110", name: "维修保养 Repairs & Maintenance" },
  { id: "6120", code: "6120", name: "运费 Shipping & Delivery" },
];

export const clients: Client[] = [
  {
    id: "c-01",
    name: "Maple Leaf Dental",
    industry: "牙科诊所",
    qboConnected: true,
    inboundEmail: "client-c01@inbound.easetax.ca",
    stats: { inbox: 3, review: 4, synced: 28 },
  },
  {
    id: "c-02",
    name: "Northwind Bistro 北风餐厅",
    industry: "餐饮",
    qboConnected: true,
    inboundEmail: "client-c02@inbound.easetax.ca",
    stats: { inbox: 6, review: 2, synced: 51 },
  },
  {
    id: "c-03",
    name: "Evergreen Landscaping",
    industry: "园林绿化",
    qboConnected: false,
    inboundEmail: "client-c03@inbound.easetax.ca",
    stats: { inbox: 2, review: 0, synced: 0 },
  },
  {
    id: "c-04",
    name: "Skyline Trading 天成贸易",
    industry: "进出口贸易",
    qboConnected: true,
    inboundEmail: "client-c04@inbound.easetax.ca",
    stats: { inbox: 1, review: 3, synced: 73 },
  },
];

const hst = (sub: number) => Math.round(sub * 0.13 * 100) / 100;

export const documents: DocumentRec[] = [
  {
    id: "d-201",
    clientId: "c-01",
    source: "email",
    fileName: "staples-invoice-88231.pdf",
    fileKind: "pdf",
    vendor: "Staples Canada",
    invoiceNo: "INV-88231",
    txnDate: "2026-06-28",
    dueDate: "2026-07-28",
    currency: "CAD",
    subTotal: 247.5,
    tax: hst(247.5),
    taxLabel: "HST 13%",
    total: 247.5 + hst(247.5),
    status: "needs_review",
    confidence: "low",
    receivedAt: "2 小时前",
    lines: [
      { id: "l1", description: "HP 碳粉盒 26A 黑色", amount: 129.0, glAccountId: "6000", glAccountName: "办公用品 Office Supplies", taxCode: "HST ON", confidence: "high" },
      { id: "l2", description: "A4 复印纸 5 包装", amount: 42.5, glAccountId: "6000", glAccountName: "办公用品 Office Supplies", taxCode: "HST ON", confidence: "high" },
      { id: "l3", description: "Logitech 无线鼠标 M330", amount: 39.99, glAccountId: null, glAccountName: null, taxCode: "HST ON", confidence: "low" },
      { id: "l4", description: "延保服务 24 个月", amount: 36.01, glAccountId: "6040", glAccountName: "软件订阅 Software & Subscriptions", taxCode: "HST ON", confidence: "medium" },
    ],
  },
  {
    id: "d-202",
    clientId: "c-01",
    source: "email",
    fileName: "bell-mobility-jun.pdf",
    fileKind: "pdf",
    vendor: "Bell Canada",
    invoiceNo: "BELL-4471902",
    txnDate: "2026-06-25",
    dueDate: "2026-07-15",
    currency: "CAD",
    subTotal: 185.0,
    tax: hst(185.0),
    taxLabel: "HST 13%",
    total: 185.0 + hst(185.0),
    status: "needs_review",
    confidence: "medium",
    receivedAt: "5 小时前",
    lines: [
      { id: "l1", description: "商务光纤网络 月费", amount: 120.0, glAccountId: "6010", glAccountName: "电话及网络 Telephone & Internet", taxCode: "HST ON", confidence: "high" },
      { id: "l2", description: "座机线路 x3", amount: 65.0, glAccountId: "6010", glAccountName: "电话及网络 Telephone & Internet", taxCode: "HST ON", confidence: "medium" },
    ],
  },
  {
    id: "d-203",
    clientId: "c-01",
    source: "upload",
    fileName: "uber-receipt.jpg",
    fileKind: "image",
    vendor: "Uber Canada",
    invoiceNo: "—",
    txnDate: "2026-06-24",
    dueDate: "2026-06-24",
    currency: "CAD",
    subTotal: 32.4,
    tax: hst(32.4),
    taxLabel: "HST 13%",
    total: 32.4 + hst(32.4),
    status: "needs_review",
    confidence: "low",
    receivedAt: "昨天",
    lines: [
      { id: "l1", description: "行程 多伦多市区 → Pearson 机场", amount: 32.4, glAccountId: null, glAccountName: null, taxCode: "HST ON", confidence: "low" },
    ],
    note: "缺发票号，收据为手机拍照",
  },
  {
    id: "d-204",
    clientId: "c-01",
    source: "email",
    fileName: "yonge-holdings-rent.pdf",
    fileKind: "pdf",
    vendor: "Yonge St Holdings",
    invoiceNo: "RENT-2026-07",
    txnDate: "2026-06-30",
    dueDate: "2026-07-01",
    currency: "CAD",
    subTotal: 3200.0,
    tax: 0,
    taxLabel: "免税",
    total: 3200.0,
    status: "needs_review",
    confidence: "high",
    receivedAt: "昨天",
    lines: [
      { id: "l1", description: "诊所月租 — 2026 年 7 月", amount: 3200.0, glAccountId: "6030", glAccountName: "租金 Rent Expense", taxCode: "免税", confidence: "high" },
    ],
  },
  {
    id: "d-205",
    clientId: "c-01",
    source: "email",
    fileName: "amazon-ca-order.pdf",
    fileKind: "pdf",
    vendor: "Amazon.ca",
    invoiceNo: "701-9928",
    txnDate: "2026-06-22",
    dueDate: "2026-06-22",
    currency: "CAD",
    subTotal: 89.97,
    tax: hst(89.97),
    taxLabel: "HST 13%",
    total: 89.97 + hst(89.97),
    status: "received",
    confidence: "medium",
    receivedAt: "3 天前",
    lines: [],
  },
  {
    id: "d-206",
    clientId: "c-01",
    source: "upload",
    fileName: "costco-receipt.jpg",
    fileKind: "image",
    vendor: "Costco Wholesale",
    invoiceNo: "—",
    txnDate: "2026-06-20",
    dueDate: "2026-06-20",
    currency: "CAD",
    subTotal: 156.32,
    tax: hst(156.32),
    taxLabel: "HST 13%",
    total: 156.32 + hst(156.32),
    status: "processing",
    confidence: "medium",
    receivedAt: "3 天前",
    lines: [],
  },
  {
    id: "d-207",
    clientId: "c-01",
    source: "email",
    fileName: "staples-invoice-88231-copy.pdf",
    fileKind: "pdf",
    vendor: "Staples Canada",
    invoiceNo: "INV-88231",
    txnDate: "2026-06-28",
    dueDate: "2026-07-28",
    currency: "CAD",
    subTotal: 247.5,
    tax: hst(247.5),
    taxLabel: "HST 13%",
    total: 247.5 + hst(247.5),
    status: "duplicate",
    confidence: "high",
    receivedAt: "1 小时前",
    lines: [],
    note: "与 INV-88231（d-201）日期+金额+供应商一致，疑似重复",
  },
  {
    id: "d-208",
    clientId: "c-01",
    source: "email",
    fileName: "shopify-subscription.pdf",
    fileKind: "pdf",
    vendor: "Shopify Inc.",
    invoiceNo: "SH-772104",
    txnDate: "2026-06-18",
    dueDate: "2026-06-18",
    currency: "CAD",
    subTotal: 79.0,
    tax: hst(79.0),
    taxLabel: "HST 13%",
    total: 79.0 + hst(79.0),
    status: "confirmed",
    confidence: "high",
    receivedAt: "5 天前",
    lines: [
      { id: "l1", description: "Shopify 月度订阅 Basic", amount: 79.0, glAccountId: "6040", glAccountName: "软件订阅 Software & Subscriptions", taxCode: "HST ON", confidence: "high" },
    ],
  },
  {
    id: "d-209",
    clientId: "c-01",
    source: "email",
    fileName: "hydro-one-may.pdf",
    fileKind: "pdf",
    vendor: "Hydro One",
    invoiceNo: "HO-55120",
    txnDate: "2026-06-15",
    dueDate: "2026-07-05",
    currency: "CAD",
    subTotal: 214.6,
    tax: hst(214.6),
    taxLabel: "HST 13%",
    total: 214.6 + hst(214.6),
    status: "synced",
    confidence: "high",
    receivedAt: "1 周前",
    lines: [
      { id: "l1", description: "诊所用电 — 5 月账期", amount: 214.6, glAccountId: "6060", glAccountName: "水电杂费 Utilities", taxCode: "HST ON", confidence: "high" },
    ],
  },
  {
    id: "d-210",
    clientId: "c-01",
    source: "email",
    fileName: "aviva-insurance-q3.pdf",
    fileKind: "pdf",
    vendor: "Aviva Insurance",
    invoiceNo: "AV-2026-Q3",
    txnDate: "2026-06-12",
    dueDate: "2026-07-12",
    currency: "CAD",
    subTotal: 540.0,
    tax: 0,
    taxLabel: "免税",
    total: 540.0,
    status: "synced",
    confidence: "high",
    receivedAt: "1 周前",
    lines: [
      { id: "l1", description: "诊所职业责任险 — 第三季度", amount: 540.0, glAccountId: "6100", glAccountName: "保险 Insurance", taxCode: "免税", confidence: "high" },
    ],
  },
  {
    id: "d-211",
    clientId: "c-01",
    source: "upload",
    fileName: "grand-toy-scan.pdf",
    fileKind: "pdf",
    vendor: "Grand & Toy",
    invoiceNo: "GT-3391",
    txnDate: "2026-06-10",
    dueDate: "2026-07-10",
    currency: "CAD",
    subTotal: 68.4,
    tax: hst(68.4),
    taxLabel: "HST 13%",
    total: 68.4 + hst(68.4),
    status: "failed",
    confidence: "low",
    receivedAt: "1 周前",
    lines: [],
    note: "OCR 连续 3 次失败 — 扫描件过暗，建议重新上传",
  },
];

// 演示用：由「模拟上传」流程产生的单据。刻意不放进 documents，
// 所以队列初始渲染不含它，只有走完上传动画后才在客户端插入。
export const demoUploadDoc: DocumentRec = {
  id: "d-demo-upload",
  clientId: "c-01",
  source: "upload",
  fileName: "home-depot-receipt.jpg",
  fileKind: "image",
  vendor: "The Home Depot",
  invoiceNo: "HD-2026-0714",
  txnDate: "2026-07-08",
  dueDate: "2026-07-08",
  currency: "CAD",
  subTotal: 176.4,
  tax: hst(176.4),
  taxLabel: "HST 13%",
  total: 176.4 + hst(176.4),
  status: "needs_review",
  confidence: "low",
  receivedAt: "刚刚",
  lines: [
    { id: "l1", description: "PVC 管件套装", amount: 48.0, glAccountId: "6110", glAccountName: "维修保养 Repairs & Maintenance", taxCode: "HST ON", confidence: "high" },
    { id: "l2", description: "LED 灯管 T8 x6", amount: 71.4, glAccountId: null, glAccountName: null, taxCode: "HST ON", confidence: "low" },
    { id: "l3", description: "工业清洁剂 5L", amount: 57.0, glAccountId: null, glAccountName: null, taxCode: "HST ON", confidence: "medium" },
  ],
  note: "演示：本单据由「模拟上传」生成，用于走通收单→识别→复核流程",
};

export function clientById(id: string) {
  return clients.find((c) => c.id === id);
}
export function documentById(id: string) {
  return [...documents, demoUploadDoc].find((d) => d.id === id);
}
export function documentsByClient(id: string) {
  return documents.filter((d) => d.clientId === id);
}
